hurl_opts := "--variables-file hurl.env.test --test"

@_list:
    just --list --unsorted

run:
    npx tailwindcss -i ./input.css -o ./assets/tailwind.css --watch &
    dx serve --hot-reload

@verify: test lint
    echo ------------ verify done! ------------

# Run the static code analysis
lint:
    cargo fmt --all -- --check
    cargo hack clippy --feature-powerset --all-targets --workspace

# Run the tests
test:
    cargo hack test --feature-powerset